# Generated by Django 5.2 on 2025-06-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_resiliencescore"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="accuracy_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.sensor"
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
