# Generated by Django 5.2 on 2025-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sensordata_accuracy_rating_alter_sensordata_sensor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
