# Generated by Django 5.2 on 2025-09-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sensor_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="barangay",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sensors", to="core.barangay"),
        ),
    ]
