# Generated by Django 5.2 on 2025-09-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_sensor_barangay_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangay",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Mark as featured to be included in periodic weather updates.",
            ),
        ),
    ]
