# Generated by Django 5.2 on 2025-10-10 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_barangay_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="floodalert",
            name="last_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="core.sensor",
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
