# Generated by Django 5.2 on 2025-10-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_floodalert_last_notification_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floodalert",
            name="scheduled_send_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when notifications should be sent. If not set, notifications are sent immediately.",
                null=True,
            ),
        ),
    ]
