# Generated by Django 5.2 on 2025-10-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_floodalert_scheduled_send_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangay",
            name="auto_alert_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable automatic alerts for this barangay"
            ),
        ),
        migrations.AddField(
            model_name="barangay",
            name="last_auto_alert_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time an automatic alert was sent for this barangay",
                null=True,
            ),
        ),
    ]
