# Generated by Django 5.2 on 2025-10-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_barangay_auto_alert_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floodalert",
            name="actions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of recommended actions for this alert",
            ),
        ),
    ]
