# Generated by Django 5.2 on 2025-10-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_floodalert_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="barangay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="core.barangay",
            ),
        ),
    ]
